In [1]:
import os
import json
import pandas as pd

In [2]:
# Table for Aggregated Transaction data for India State-wise

path = "pulse/data/aggregated/transaction/country/india/state/"

Agg_trans = {
    "State":[], "Year":[], "Quarter":[],
    "Transaction_type":[], "Transaction_count":[], "Transaction_amount":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):  
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                try:
                    for i in data['data']['transactionData']:
                        Agg_trans["State"].append(state)
                        Agg_trans["Year"].append(int(year))
                        Agg_trans["Quarter"].append(int(file.strip(".json")))
                        Agg_trans["Transaction_type"].append(i['name'])
                        Agg_trans["Transaction_count"].append(i['paymentInstruments'][0]['count'])
                        Agg_trans["Transaction_amount"].append(i['paymentInstruments'][0]['amount'])
                except:
                    pass

df_Agg_trans = pd.DataFrame(Agg_trans)
df_Agg_trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [3]:
# Table for Aggregated User data for India State-wise

path = "pulse/data/aggregated/user/country/india/state/"

Agg_user = {
    "State":[], "Year":[], "Quarter":[],
    "Brand":[], "Count":[], "Percentage":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                try:
                    for i in data['data']['usersByDevice']:
                        Agg_user["State"].append(state)
                        Agg_user["Year"].append(int(year))
                        Agg_user["Quarter"].append(int(file.strip(".json")))
                        Agg_user["Brand"].append(i['brand'])
                        Agg_user["Count"].append(i['count'])
                        Agg_user["Percentage"].append(i['percentage'])
                except:
                    pass

df_Agg_user = pd.DataFrame(Agg_user)
df_Agg_user

                          State  Year  Quarter    Brand    Count  Percentage
0     andaman-&-nicobar-islands  2018        1   Xiaomi     1665    0.247033
1     andaman-&-nicobar-islands  2018        1  Samsung     1445    0.214392
2     andaman-&-nicobar-islands  2018        1     Vivo      982    0.145697
3     andaman-&-nicobar-islands  2018        1     Oppo      501    0.074332
4     andaman-&-nicobar-islands  2018        1  OnePlus      332    0.049258
...                         ...   ...      ...      ...      ...         ...
6727                west-bengal  2022        1   Lenovo   330017    0.015056
6728                west-bengal  2022        1  Infinix   284678    0.012987
6729                west-bengal  2022        1     Asus   280347    0.012790
6730                west-bengal  2022        1    Apple   277752    0.012671
6731                west-bengal  2022        1   Others  2196334    0.100199

[6732 rows x 6 columns]

In [4]:
# Table for Aggregated Insurance data for India State-wise

path = "pulse/data/aggregated/insurance/country/india/state/"

Agg_ins = {
    "State":[], "Year":[], "Quarter":[],
    "Insurance_type":[], "Count":[], "Amount":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                try:
                    for i in data['data']['transactionData']:
                        Agg_ins["State"].append(state)
                        Agg_ins["Year"].append(int(year))
                        Agg_ins["Quarter"].append(int(file.strip(".json")))
                        Agg_ins["Insurance_type"].append(i['name'])
                        Agg_ins["Count"].append(i['paymentInstruments'][0]['count'])
                        Agg_ins["Amount"].append(i['paymentInstruments'][0]['amount'])
                except:
                    pass

df_Agg_ins = pd.DataFrame(Agg_ins)
df_Agg_ins

,State,Year,Quarter,Insurance_type,Count,Amount
0,andaman-&-nicobar-islands,2020,2,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,west-bengal,2023,4,Insurance,72712,100365562.0
678,west-bengal,2024,1,Insurance,79576,104987909.0
679,west-bengal,2024,2,Insurance,67048,89476633.0
680,west-bengal,2024,3,Insurance,77158,107451766.0
681,west-bengal,2024,4,Insurance,91719,120602777.0