In [1]:
import os
import json
import pandas as pd

In [2]:
# Table for Map_Transaction data for India State-wise

path = "pulse/data/map/transaction/hover/country/india/state/"

Map_trans = {
    "State":[], "Year":[], "Quarter":[],
    "District":[], "Count":[], "Amount":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                try:
                    for i in data['data']['hoverDataList']:
                        Map_trans["State"].append(state)
                        Map_trans["Year"].append(int(year))
                        Map_trans["Quarter"].append(int(file.strip(".json")))
                        Map_trans["District"].append(i['name'])
                        Map_trans["Count"].append(i['metric'][0]['count'])
                        Map_trans["Amount"].append(i['metric'][0]['amount'])
                except:
                    pass

df_Map_trans = pd.DataFrame(Map_trans)
df_Map_trans

,State,Year,Quarter,District,Count,Amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia district,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [3]:
# Table for Map_User data for India State-wise

path = "pulse/data/map/user/hover/country/india/state/"

Map_user = {
    "State":[], "Year":[], "Quarter":[],
    "District":[], "Registered_Users":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                try:
                    for district, details in data['data']['hoverData'].items():
                        Map_user["State"].append(state)
                        Map_user["Year"].append(int(year))
                        Map_user["Quarter"].append(int(file.strip(".json")))
                        Map_user["District"].append(district)
                        Map_user["Registered_Users"].append(details['registeredUsers'])
                except:
                    pass

df_Map_user = pd.DataFrame(Map_user)
df_Map_user

,State,Year,Quarter,District,Registered_Users
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846
2,andaman-&-nicobar-islands,2018,1,nicobars district,262
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143
...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688
20604,west-bengal,2024,4,paschim bardhaman district,1468252
20605,west-bengal,2024,4,nadia district,1861738
20606,west-bengal,2024,4,birbhum district,1114220
20607,west-bengal,2024,4,purba medinipur district,1717074

In [4]:
# Table for Map_Insurance data for India State-wise

path = "pulse/data/map/insurance/hover/country/india/state/"

Map_ins = {
    "State":[], "Year":[], "Quarter":[],
    "District":[], "Count":[], "Amount":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                try:
                    for i in data['data']['hoverDataList']:
                        Map_ins["State"].append(state)
                        Map_ins["Year"].append(int(year))
                        Map_ins["Quarter"].append(int(file.strip(".json")))
                        Map_ins["District"].append(i['name'])
                        Map_ins["Count"].append(i['metric'][0]['count'])
                        Map_ins["Amount"].append(i['metric'][0]['amount'])
                except:
                    pass

df_Map_ins = pd.DataFrame(Map_ins)
df_Map_ins

,State,Year,Quarter,District,Count,Amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,west-bengal,2024,4,nadia district,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,3559,4439061.0